### ISSUE TITLE
turkish letter

### ISSUE THREAD

**Issue by requizm** [NaylonBrando/GameMarketDemo#1]
https://github.com/NaylonBrando/GameMarketDemo/blob/ed5091978624b3cda8225ac11881a5ceea725bba/GameMarketDemo/Program.cs#L12

Hi~~
So Senpai, thewe is this issue I've been having in project
I have 2 bluetooth adaptows and when I switch between them, the 3 bars that tell the signal stwength fow cuwwently connected devices disappear (；⌣̀_⌣́)

Don't wowwy though, I got it all mapped out! 🎶🎶💕

**Comment by requizm** [comment]
gaycum sir

**Comment by requizm** [comment]
fa

**Comment by NaylonBrando** [comment]
no
